eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
server:
  port: 9013
spring:
  application:
    name: service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: c27ae251-cc1e-4523-b4a8-c5b9bd9a3896
    sentinel:
      transport:
        # 添加sentinel的控制台地址
        dashboard: 127.0.0.1:8080
        # 指定应用与Sentinel控制台交互的端口，应用本地会起一个该端口占用的HttpServer
        port: 8719
  #  不能有eureka和nacos两个注册中心，排除一个
  autoconfigure:
    exclude: org.springframework.cloud.netflix.eureka.EurekaClientAutoConfiguration
#暴露actuator端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com:
      horkr: debug

custom.turnon: 54321
feign:
  connect:
    timeout:
      millis: 30000
  #  使用httpClient才有连接池，开启以优化feign
  httpclient:
    enabled: true
    #    最大连接数
    max-connections: 200
    #    每个url的最大连接数
    max-connections-per-route: 50
