---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/11/23 17:03
---

--引入redis模块，类似java的包,openResty的luaLib中已经引入了redis.lua
local redis = require "redis.redis"
-- 创建redis 示例
local redisInstance =  redis:new()
-- 开始连接
local ok,err = redisInstance:connect("127.0.0.1",6379)

if not ok then ngx.say("connect fail: ",err)  return end

ok,err = redisInstance:set("dog","an animal")
if not ok then ngx.say("fail to set dog: ",err)  return end
ngx.say("set result: ",ok)
local res,err = redisInstance:get("dog")
if not res then ngx.say("fail to get dog: ",err)  return end
if res == ngx.null then ngx.say("dog not found")  return end
ngx.say("dog: ",res) return