server:
  port: 10001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/pcp_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone = GMT
  redis:
    redisson:
      file: classpath:redisson.yml
  kafka:
    producer:
      retries: 3
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 40960
      #批处理条数：当多个记录被发送到同一个分区时，生产者会尝试将记录合并到更少的请求中。这有助于客户端和服务器的性能
      batch-size: 4096

    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 批量接收数据时最多的条数
      max-poll-records: 10
    listener:
      #      多个消费者（即多线程）,一个线程对应一个分区，若只有一个分区，则只有一个线程
      #      批量处理（即每次获取到指定数目数据再返回，与max-poll-records对应）
      concurrency: 1
      type: batch
      ack-mode: manual
    bootstrap-servers: localhost:9092
  rocketmq:
    name-server: 127.0.0.1:9876
  aop:
    proxy-target-class: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

